name: release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build release binary + Debian package
      run: cargo deb --no-strip -o target/debian/spotify-adblock-amd64.deb
    - name: Upload build artifact to release
      run: |
        gh release upload \
        "${{ github.event.release.tag_name }}" \
        target/release/libspotifyadblock.so \
        target/debian/spotify-adblock-amd64.deb \
        --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
